import nodemailer from 'nodemailer';

export const sendEmailReminder = async (toEmail, subject, textBody) => {
  const smtpHost = process.env.SMTP_HOST || 'smtp.gmail.com';
  const smtpPort = parseInt(process.env.SMTP_PORT || '587');
  const smtpUser = process.env.SMTP_USER;
  const smtpPass = process.env.SMTP_PASS;

  const isConfigured = Boolean(
    smtpHost &&
    smtpUser &&
    smtpPass &&
    smtpUser !== 'your_email@gmail.com' &&
    smtpPass !== 'your_gmail_app_password'
  );

  if (!isConfigured) {
    console.log(`[MAIL] SMTP credentials not configured in server/.env. Skipping real send for: ${toEmail}`);
    return { success: false, status: 'failed', error: 'SMTP credentials not configured in server/.env', recipient: toEmail };
  }

  try {
    const transporter = nodemailer.createTransport({
      host: smtpHost,
      port: smtpPort,
      secure: smtpPort === 465,
      auth: {
        user: smtpUser,
        pass: smtpPass
      }
    });

    const info = await transporter.sendMail({
      from: process.env.SMTP_FROM || `"Revive AI Revenue Recovery" <${smtpUser}>`,
      to: toEmail,
      subject: subject || 'Revive: Action Required for Pending Payment',
      text: textBody,
      html: `
        <div style="font-family: Arial, sans-serif; background-color: #FBF8EF; padding: 20px; border: 2px solid #1A2B4C; border-radius: 8px;">
          <h2 style="color: #0F2042; border-bottom: 2px solid #D9383A; padding-bottom: 8px;">REVIVE — AI Revenue Recovery</h2>
          <p style="font-size: 15px; color: #1A2B4C; line-height: 1.6;">${textBody}</p>
          <hr style="border: 0; border-top: 1px solid #E2D9C8; margin-top: 20px;" />
          <p style="font-size: 11px; color: #5A6578; font-style: italic;">
            This notification was generated by Revive Autonomous Revenue Recovery Agent.
          </p>
        </div>
      `
    });

    console.log(`[MAIL] Real email successfully delivered to ${toEmail}. Message ID: ${info.messageId}`);
    return { success: true, status: 'sent', messageId: info.messageId, recipient: toEmail };
  } catch (err) {
    console.warn(`[MAIL] SMTP delivery attempt failed to ${toEmail} (${err.message})`);
    return { success: false, status: 'failed', error: err.message, recipient: toEmail };
  }
};
